apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: shipping-system
data:
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=1f3a1dfd-cf0b-4111-92ed-b118098b25b9;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=5ff27e9e-11e1-4c74-9395-15ee64f5cffd"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_PROPAGATORS: "tracecontext,baggage"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production,k8s.cluster.name=aks-demo,k8s.namespace.name=shipping-system"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: analytics-system
data:
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=1f3a1dfd-cf0b-4111-92ed-b118098b25b9;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=5ff27e9e-11e1-4c74-9395-15ee64f5cffd"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_PROPAGATORS: "tracecontext,baggage"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production,k8s.cluster.name=aks-demo,k8s.namespace.name=analytics-system"
